import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Us Page",
    description: "Generated by create next app",
    keywords: ['About Page', 'Next.js', 'Create Next App'],
  };

export default function AboutPage() {
    return (
        <div>
            <h1>About Page</h1>
        </div>
    )
}